# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_test.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWind(object):
    def setupUi(self, mainWind):
        mainWind.setObjectName(_fromUtf8("mainWind"))
        mainWind.resize(737, 552)
        mainWind.setMinimumSize(QtCore.QSize(0, 40))
        mainWind.setMaximumSize(QtCore.QSize(16777215, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/logo_resize.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWind.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(mainWind)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(mainWind)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.reg_pid_frame = QtGui.QFrame(self.groupBox)
        self.reg_pid_frame.setMaximumSize(QtCore.QSize(16777215, 110))
        self.reg_pid_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.reg_pid_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.reg_pid_frame.setObjectName(_fromUtf8("reg_pid_frame"))
        self.gridLayout = QtGui.QGridLayout(self.reg_pid_frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_D = QtGui.QLabel(self.reg_pid_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_D.setFont(font)
        self.label_D.setTextFormat(QtCore.Qt.AutoText)
        self.label_D.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_D.setObjectName(_fromUtf8("label_D"))
        self.gridLayout.addWidget(self.label_D, 2, 2, 1, 2)
        self.doubleSpinBox_I = QtGui.QDoubleSpinBox(self.reg_pid_frame)
        self.doubleSpinBox_I.setMinimumSize(QtCore.QSize(0, 20))
        self.doubleSpinBox_I.setObjectName(_fromUtf8("doubleSpinBox_I"))
        self.gridLayout.addWidget(self.doubleSpinBox_I, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.label_title_pid = QtGui.QLabel(self.reg_pid_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_title_pid.setFont(font)
        self.label_title_pid.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_pid.setObjectName(_fromUtf8("label_title_pid"))
        self.gridLayout.addWidget(self.label_title_pid, 0, 0, 1, 3)
        self.doubleSpinBox_D = QtGui.QDoubleSpinBox(self.reg_pid_frame)
        self.doubleSpinBox_D.setMinimumSize(QtCore.QSize(0, 20))
        self.doubleSpinBox_D.setObjectName(_fromUtf8("doubleSpinBox_D"))
        self.gridLayout.addWidget(self.doubleSpinBox_D, 3, 2, 1, 2)
        self.label_P = QtGui.QLabel(self.reg_pid_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_P.setFont(font)
        self.label_P.setTextFormat(QtCore.Qt.AutoText)
        self.label_P.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_P.setObjectName(_fromUtf8("label_P"))
        self.gridLayout.addWidget(self.label_P, 2, 0, 1, 1)
        self.label_I = QtGui.QLabel(self.reg_pid_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_I.setFont(font)
        self.label_I.setTextFormat(QtCore.Qt.AutoText)
        self.label_I.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_I.setObjectName(_fromUtf8("label_I"))
        self.gridLayout.addWidget(self.label_I, 2, 1, 1, 1)
        self.doubleSpinBox_P = QtGui.QDoubleSpinBox(self.reg_pid_frame)
        self.doubleSpinBox_P.setMinimumSize(QtCore.QSize(0, 20))
        self.doubleSpinBox_P.setObjectName(_fromUtf8("doubleSpinBox_P"))
        self.gridLayout.addWidget(self.doubleSpinBox_P, 3, 0, 1, 1)
        self.send_pid_Button = QtGui.QCheckBox(self.reg_pid_frame)
        self.send_pid_Button.setObjectName(_fromUtf8("send_pid_Button"))
        self.gridLayout.addWidget(self.send_pid_Button, 0, 3, 1, 1)
        self.horizontalLayout.addWidget(self.reg_pid_frame)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.position_frame_2 = QtGui.QFrame(self.groupBox)
        self.position_frame_2.setMaximumSize(QtCore.QSize(16777215, 110))
        self.position_frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.position_frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.position_frame_2.setObjectName(_fromUtf8("position_frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.position_frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_pos_x = QtGui.QLabel(self.position_frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_pos_x.setFont(font)
        self.label_pos_x.setTextFormat(QtCore.Qt.AutoText)
        self.label_pos_x.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_pos_x.setObjectName(_fromUtf8("label_pos_x"))
        self.gridLayout_2.addWidget(self.label_pos_x, 3, 2, 1, 1)
        self.doubleSpinBox_y = QtGui.QDoubleSpinBox(self.position_frame_2)
        self.doubleSpinBox_y.setMinimumSize(QtCore.QSize(0, 20))
        self.doubleSpinBox_y.setObjectName(_fromUtf8("doubleSpinBox_y"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_y, 5, 5, 1, 1)
        self.label_pos = QtGui.QLabel(self.position_frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_pos.setFont(font)
        self.label_pos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pos.setObjectName(_fromUtf8("label_pos"))
        self.gridLayout_2.addWidget(self.label_pos, 0, 2, 1, 1)
        self.label_pos_y = QtGui.QLabel(self.position_frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_pos_y.setFont(font)
        self.label_pos_y.setTextFormat(QtCore.Qt.AutoText)
        self.label_pos_y.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_pos_y.setObjectName(_fromUtf8("label_pos_y"))
        self.gridLayout_2.addWidget(self.label_pos_y, 3, 5, 1, 1)
        self.doubleSpinBox_x = QtGui.QDoubleSpinBox(self.position_frame_2)
        self.doubleSpinBox_x.setMinimumSize(QtCore.QSize(0, 20))
        self.doubleSpinBox_x.setObjectName(_fromUtf8("doubleSpinBox_x"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_x, 5, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        self.send_pos = QtGui.QCheckBox(self.position_frame_2)
        self.send_pos.setObjectName(_fromUtf8("send_pos"))
        self.gridLayout_2.addWidget(self.send_pos, 0, 5, 1, 1)
        self.horizontalLayout.addWidget(self.position_frame_2)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.send_data = QtGui.QFrame(self.groupBox)
        self.send_data.setMaximumSize(QtCore.QSize(16777215, 110))
        self.send_data.setFrameShape(QtGui.QFrame.StyledPanel)
        self.send_data.setFrameShadow(QtGui.QFrame.Raised)
        self.send_data.setObjectName(_fromUtf8("send_data"))
        self.gridLayout_3 = QtGui.QGridLayout(self.send_data)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_data = QtGui.QLabel(self.send_data)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_data.setFont(font)
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName(_fromUtf8("label_data"))
        self.gridLayout_3.addWidget(self.label_data, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 1, 0, 1, 1)
        self.label_adr = QtGui.QLabel(self.send_data)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_adr.setFont(font)
        self.label_adr.setTextFormat(QtCore.Qt.AutoText)
        self.label_adr.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_adr.setObjectName(_fromUtf8("label_adr"))
        self.gridLayout_3.addWidget(self.label_adr, 2, 0, 1, 1)
        self.label_data_value = QtGui.QLabel(self.send_data)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_data_value.setFont(font)
        self.label_data_value.setTextFormat(QtCore.Qt.AutoText)
        self.label_data_value.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_data_value.setObjectName(_fromUtf8("label_data_value"))
        self.gridLayout_3.addWidget(self.label_data_value, 2, 1, 1, 1)
        self.comboBox_adr = QtGui.QComboBox(self.send_data)
        self.comboBox_adr.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_adr.setObjectName(_fromUtf8("comboBox_adr"))
        self.gridLayout_3.addWidget(self.comboBox_adr, 3, 0, 1, 1)
        self.spinBox_data_value = QtGui.QSpinBox(self.send_data)
        self.spinBox_data_value.setMinimumSize(QtCore.QSize(0, 20))
        self.spinBox_data_value.setObjectName(_fromUtf8("spinBox_data_value"))
        self.gridLayout_3.addWidget(self.spinBox_data_value, 3, 1, 1, 1)
        self.send_data_Button = QtGui.QCheckBox(self.send_data)
        self.send_data_Button.setObjectName(_fromUtf8("send_data_Button"))
        self.gridLayout_3.addWidget(self.send_data_Button, 0, 1, 1, 1)
        self.label_data.raise_()
        self.send_data_Button.raise_()
        self.spinBox_data_value.raise_()
        self.comboBox_adr.raise_()
        self.label_adr.raise_()
        self.label_data_value.raise_()
        self.horizontalLayout.addWidget(self.send_data)
        spacerItem6 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame_recie = QtGui.QFrame(mainWind)
        self.frame_recie.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_recie.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_recie.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_recie.setObjectName(_fromUtf8("frame_recie"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_recie)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.widget = QtGui.QWidget(self.frame_recie)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_adr_rec = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_adr_rec.setFont(font)
        self.label_adr_rec.setTextFormat(QtCore.Qt.AutoText)
        self.label_adr_rec.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adr_rec.setObjectName(_fromUtf8("label_adr_rec"))
        self.verticalLayout_2.addWidget(self.label_adr_rec)
        self.comboBox_adr_rec = QtGui.QComboBox(self.widget)
        self.comboBox_adr_rec.setObjectName(_fromUtf8("comboBox_adr_rec"))
        self.verticalLayout_2.addWidget(self.comboBox_adr_rec)
        self.affich_pid = QtGui.QGroupBox(self.widget)
        self.affich_pid.setObjectName(_fromUtf8("affich_pid"))
        self.formLayout = QtGui.QFormLayout(self.affich_pid)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_p = QtGui.QLabel(self.affich_pid)
        self.label_p.setObjectName(_fromUtf8("label_p"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_p)
        self.label_pv = QtGui.QLabel(self.affich_pid)
        self.label_pv.setObjectName(_fromUtf8("label_pv"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_pv)
        self.label_i = QtGui.QLabel(self.affich_pid)
        self.label_i.setObjectName(_fromUtf8("label_i"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_i)
        self.label_iv = QtGui.QLabel(self.affich_pid)
        self.label_iv.setObjectName(_fromUtf8("label_iv"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_iv)
        self.label_d = QtGui.QLabel(self.affich_pid)
        self.label_d.setObjectName(_fromUtf8("label_d"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_d)
        self.label_dv = QtGui.QLabel(self.affich_pid)
        self.label_dv.setObjectName(_fromUtf8("label_dv"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_dv)
        self.verticalLayout_2.addWidget(self.affich_pid)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.start_Button = QtGui.QPushButton(self.widget)
        self.start_Button.setObjectName(_fromUtf8("start_Button"))
        self.verticalLayout_2.addWidget(self.start_Button)
        self.horizontalLayout_5.addWidget(self.widget)
        self.graphicsView = GraphicsLayoutWidget(self.frame_recie)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout_5.addWidget(self.graphicsView)
        self.verticalLayout.addWidget(self.frame_recie)
        self.frame_2 = QtGui.QFrame(mainWind)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(10, 0, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(250, 50))
        self.frame.setMaximumSize(QtCore.QSize(250, 50))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(100, 50))
        self.label.setMaximumSize(QtCore.QSize(125, 75))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("img/logo_resize.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.save_button = QtGui.QPushButton(self.groupBox_2)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.horizontalLayout_2.addWidget(self.save_button)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.exit_button = QtGui.QPushButton(self.groupBox_2)
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.horizontalLayout_2.addWidget(self.exit_button)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.horizontalLayout_4.addWidget(self.frame)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.lineEdit_portcom = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_portcom.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_portcom.setMaximumSize(QtCore.QSize(150, 20))
        self.lineEdit_portcom.setInputMask(_fromUtf8(""))
        self.lineEdit_portcom.setObjectName(_fromUtf8("lineEdit_portcom"))
        self.horizontalLayout_4.addWidget(self.lineEdit_portcom)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(mainWind)
        QtCore.QObject.connect(self.exit_button, QtCore.SIGNAL(_fromUtf8("clicked()")), mainWind.close)
        QtCore.QMetaObject.connectSlotsByName(mainWind)

    def retranslateUi(self, mainWind):
        mainWind.setWindowTitle(_translate("mainWind", "CRUBS la tanche qui parle", None))
        mainWind.setTitle(_translate("mainWind", "CrUbs com", None))
        self.groupBox.setTitle(_translate("mainWind", "envoie", None))
        self.label_D.setText(_translate("mainWind", "D", None))
        self.label_title_pid.setText(_translate("mainWind", "réglage du PID", None))
        self.label_P.setText(_translate("mainWind", "P", None))
        self.label_I.setText(_translate("mainWind", "I", None))
        self.send_pid_Button.setText(_translate("mainWind", "send", None))
        self.label_pos_x.setText(_translate("mainWind", "X", None))
        self.label_pos.setText(_translate("mainWind", "Position", None))
        self.label_pos_y.setText(_translate("mainWind", "Y", None))
        self.send_pos.setText(_translate("mainWind", "send", None))
        self.label_data.setText(_translate("mainWind", "send data", None))
        self.label_adr.setText(_translate("mainWind", "adresse", None))
        self.label_data_value.setText(_translate("mainWind", "valeur", None))
        self.send_data_Button.setText(_translate("mainWind", "send", None))
        self.label_adr_rec.setText(_translate("mainWind", "adresse", None))
        self.affich_pid.setTitle(_translate("mainWind", "PID status", None))
        self.label_p.setText(_translate("mainWind", "P =", None))
        self.label_pv.setText(_translate("mainWind", "TextLabel", None))
        self.label_i.setText(_translate("mainWind", "I = ", None))
        self.label_iv.setText(_translate("mainWind", "TextLabel", None))
        self.label_d.setText(_translate("mainWind", "D =", None))
        self.label_dv.setText(_translate("mainWind", "TextLabel", None))
        self.start_Button.setText(_translate("mainWind", "start", None))
        self.groupBox_2.setTitle(_translate("mainWind", "GroupBox", None))
        self.save_button.setText(_translate("mainWind", "save", None))
        self.exit_button.setText(_translate("mainWind", "exit", None))
        self.lineEdit_portcom.setText(_translate("mainWind", "/dev/ttyUSB", None))

from pyqtgraph import GraphicsLayoutWidget
